default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: user_db
  database: task_manager_db_development

development:
  <<: *default

test:
  <<: *default
  database: task_manager_db_test

production:
  <<: *default
  database: task_manager_db_production